name: Semgrep SAST Scan

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Semgrep
        run: pip install semgrep

      - name: Create reports folder
        run: mkdir -p reports/semgrep

      - name: Run Semgrep
        run: semgrep scan --config "p/default" . --json --output reports/semgrep/semgrep-sast-report.json || true

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-sast-report
          path: reports/semgrep/semgrep-sast-report.json
